# Generated by Django 5.1.1 on 2024-10-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapbetinfo',
            name='odd',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='moneylinebetinfo',
            name='odd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='totalgoalsbetinfo',
            name='odd',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
