# Generated by Django 5.1.1 on 2024-11-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_id_home_team',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(unique=True),
        ),
    ]
