# Generated by Django 5.1.2 on 2024-12-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0002_remove_match_unique_id_home_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='userhandicapbet',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='The date this handicap bet was created'),
        ),
        migrations.AddField(
            model_name='usermoneylinebet',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='The date this moneyline bet was created'),
        ),
        migrations.AddField(
            model_name='usertotalgoalsbet',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='The date this total goals bet was created'),
        ),
    ]
