# Generated by Django 5.1.2 on 2024-12-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0004_userhandicapbet_payout_usermoneylinebet_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN')], max_length=100)),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('num_watches', models.IntegerField()),
                ('num_wins', models.IntegerField()),
                ('num_loses', models.IntegerField()),
                ('num_draws', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccerapp.team')),
            ],
            options={
                'ordering': ['league', 'rank'],
            },
        ),
    ]
