# Generated by Django 5.1.2 on 2024-12-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0005_teamranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalgoalsbetinfo',
            name='target_num_goals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
