# Generated by Django 5.1.2 on 2024-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0006_alter_totalgoalsbetinfo_target_num_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cards',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='corners',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='possesion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_shots',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
