# Generated by Django 5.1.2 on 2024-12-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0007_match_cards_match_corners_match_possesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicapbetinfo',
            name='bet_object',
            field=models.CharField(choices=[('Goals', 'Goals'), ('Corners', 'Corners'), ('Cards', 'Cards')], default='Goals', max_length=50),
        ),
        migrations.AddField(
            model_name='moneylinebetinfo',
            name='bet_object',
            field=models.CharField(choices=[('Goals', 'Goals'), ('Corners', 'Corners'), ('Cards', 'Cards')], default='Goals', max_length=50),
        ),
        migrations.AddField(
            model_name='totalgoalsbetinfo',
            name='bet_object',
            field=models.CharField(choices=[('Goals', 'Goals'), ('Corners', 'Corners'), ('Cards', 'Cards')], default='Goals', max_length=50),
        ),
    ]
