# Generated by Django 5.1.2 on 2024-12-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0008_handicapbetinfo_bet_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalGoalsBetInfo',
            new_name='TotalObjectsBetInfo',
        ),
        migrations.RenameModel(
            old_name='UserTotalGoalsBet',
            new_name='UserTotalObjectsBet',
        ),
        migrations.RenameField(
            model_name='totalobjectsbetinfo',
            old_name='target_num_goals',
            new_name='target_num_objects',
        ),
    ]
