# Generated by Django 5.1.2 on 2025-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyToUsername',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
