# Generated by Django 5.1.2 on 2025-01-22 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0013_alter_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
