# Generated by Django 5.1.2 on 2025-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0016_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapbetinfo',
            name='time_type',
            field=models.CharField(choices=[('Full-time', 'full_time'), ('Half-time', 'half_time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN'), ('Serie A', 'SER'), ('League 1', 'LEA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='moneylinebetinfo',
            name='time_type',
            field=models.CharField(choices=[('Full-time', 'full_time'), ('Half-time', 'half_time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN'), ('Serie A', 'SER'), ('League 1', 'LEA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Logo of the team'),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='league',
            field=models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN'), ('Serie A', 'SER'), ('League 1', 'LEA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='totalobjectsbetinfo',
            name='time_type',
            field=models.CharField(choices=[('Full-time', 'full_time'), ('Half-time', 'half_time')], max_length=50),
        ),
    ]
