# Generated by Django 5.1.2 on 2025-10-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0017_alter_handicapbetinfo_time_type_alter_match_league_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replyToUsername',
        ),
        migrations.AddField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='soccerapp.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replyToComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='soccerapp.comment'),
        ),
    ]
