# Generated by Django 5.1.2 on 2025-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0018_remove_comment_replytousername_comment_parentcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapbetinfo',
            name='settled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhandicapbet',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermoneylinebet',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertotalobjectsbet',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
