# Generated by Django 5.1.2 on 2025-11-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0019_alter_handicapbetinfo_settled_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['started_at']},
        ),
        migrations.RenameField(
            model_name='handicapbetinfo',
            old_name='handicap_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='handicapbetinfo',
            old_name='settled_date',
            new_name='settled_at',
        ),
        migrations.RenameField(
            model_name='teamranking',
            old_name='num_watches',
            new_name='num_matches',
        ),
        migrations.RenameField(
            model_name='totalobjectsbetinfo',
            old_name='target_num_objects',
            new_name='num_objects',
        ),
        migrations.RenameField(
            model_name='userhandicapbet',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usermoneylinebet',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usertotalobjectsbet',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='handicapbetinfo',
            name='time_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='match',
            name='corners',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fulltime_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='halftime_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='match',
            name='possesion',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_shots',
        ),
        migrations.RemoveField(
            model_name='match',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='moneylinebetinfo',
            name='settled_date',
        ),
        migrations.RemoveField(
            model_name='moneylinebetinfo',
            name='time_type',
        ),
        migrations.RemoveField(
            model_name='totalobjectsbetinfo',
            name='settled_date',
        ),
        migrations.RemoveField(
            model_name='totalobjectsbetinfo',
            name='time_type',
        ),
        migrations.AddField(
            model_name='handicapbetinfo',
            name='period',
            field=models.CharField(choices=[('Full-time', 'full_time'), ('Half-time', 'half_time')], default='Full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moneylinebetinfo',
            name='period',
            field=models.CharField(choices=[('Full-time', 'full_time'), ('Half-time', 'half_time')], default='Full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='moneylinebetinfo',
            name='settled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalobjectsbetinfo',
            name='period',
            field=models.CharField(choices=[('Full-time', 'full_time'), ('Half-time', 'half_time')], default='Full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='totalobjectsbetinfo',
            name='settled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handicapbetinfo',
            name='bet_object',
            field=models.CharField(choices=[('Goals', 'Goals'), ('Corners', 'Corners'), ('Cards', 'Cards')], default='Goals', max_length=20),
        ),
        migrations.AlterField(
            model_name='handicapbetinfo',
            name='bet_team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='soccerapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='soccerapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN'), ('Serie A', 'SER'), ('Ligue 1', 'LEA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Not Finished', 'NF'), ('Finished', 'FN')], default='Not Finished', max_length=20),
        ),
        migrations.AlterField(
            model_name='moneylinebetinfo',
            name='bet_object',
            field=models.CharField(choices=[('Goals', 'Goals'), ('Corners', 'Corners'), ('Cards', 'Cards')], default='Goals', max_length=20),
        ),
        migrations.AlterField(
            model_name='moneylinebetinfo',
            name='bet_team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moneylinebetinfo',
            name='status',
            field=models.CharField(choices=[('Unsettled', 'UN'), ('Settled', 'SE')], default='Unsettled', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_stadium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN'), ('Serie A', 'SER'), ('Ligue 1', 'LEA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='league',
            field=models.CharField(choices=[('Champions League', 'UCL'), ('Premiere League', 'EPL'), ('La Liga', 'LAL'), ('Bundesliga', 'BUN'), ('Serie A', 'SER'), ('Ligue 1', 'LEA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='totalobjectsbetinfo',
            name='status',
            field=models.CharField(choices=[('Unsettled', 'UN'), ('Settled', 'SE')], default='Unsettled', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usermoneylinebet',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usermoneylinebet',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Halftime score', 'halftime_score'), ('Fulltime score', 'fulltime_score'), ('Penalty', 'penalty'), ('Possesion', 'possesion'), ('Total shots', 'total_shots'), ('Corners', 'corners'), ('Yellow cards', 'yellow_cards')], max_length=50)),
                ('home_stat', models.IntegerField()),
                ('away_stat', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccerapp.match')),
            ],
        ),
    ]
