# Generated by Django 5.1.2 on 2025-11-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0020_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
