# Generated by Django 5.1.2 on 2025-11-16 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0021_alter_team_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 22, 1, 33, 202776)),
        ),
    ]
