# Generated by Django 5.1.2 on 2025-11-16 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0023_alter_match_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 23, 42, 27, 208493)),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 23, 42, 27, 208475)),
        ),
    ]
