# Generated by Django 5.1.2 on 2025-11-17 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0024_match_updated_at_alter_match_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 0, 20, 58, 340143)),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 0, 20, 58, 340161)),
        ),
        migrations.AlterField(
            model_name='matchstat',
            name='away_stat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchstat',
            name='home_stat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
